.TH "/home/oco/Documents/Cprojects/Athletes/projecto - V2/Headers/BST.h" 3 "Tue Dec 27 2016" "Version 2" "Projeto AEDA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/oco/Documents/Cprojects/Athletes/projecto - V2/Headers/BST.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <stack>\fP
.br
\fC#include <queue>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBSTItrIn< Comparable >\fP"
.br
.ti -1c
.RI "class \fBBSTItrPre< Comparable >\fP"
.br
.ti -1c
.RI "class \fBBSTItrPost< Comparable >\fP"
.br
.ti -1c
.RI "class \fBBSTItrLevel< Comparable >\fP"
.br
.ti -1c
.RI "class \fBBST< Comparable >\fP"
.br
.ti -1c
.RI "class \fBBinaryNode< Comparable >\fP"
.br
.ti -1c
.RI "class \fBBST< Comparable >\fP"
.br
.ti -1c
.RI "class \fBBSTItrPost< Comparable >\fP"
.br
.ti -1c
.RI "class \fBBSTItrPre< Comparable >\fP"
.br
.ti -1c
.RI "class \fBBSTItrIn< Comparable >\fP"
.br
.ti -1c
.RI "class \fBBSTItrLevel< Comparable >\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Ana Paula Rocha 
.PP
Henrique Cardoso 
.PP
Rosaldo Rossetii
.RE
.PP
Contains the declaration of the class \fBBST\fP This file is available on Moodle\&. 
.PP
Definition in file \fBBST\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Projeto AEDA from the source code\&.
