.TH "BSTItrPost< Comparable >" 3 "Tue Dec 27 2016" "Version 2" "Projeto AEDA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BSTItrPost< Comparable > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BST\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBSTItrPost\fP (const \fBBST\fP< Comparable > &bt)"
.br
.ti -1c
.RI "void \fBadvance\fP ()"
.br
.ti -1c
.RI "Comparable & \fBretrieve\fP ()"
.br
.ti -1c
.RI "bool \fBisAtEnd\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class Comparable>
.br
class BSTItrPost< Comparable >"

.PP
Definition at line 29 of file BST\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class Comparable > \fBBSTItrPost\fP< Comparable >::\fBBSTItrPost\fP (const \fBBST\fP< Comparable > & bt)"

.PP
Definition at line 344 of file BST\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<class Comparable > void \fBBSTItrPost\fP< Comparable >::advance ()"

.PP
Definition at line 351 of file BST\&.h\&.
.SS "template<class Comparable > bool \fBBSTItrPost\fP< Comparable >::isAtEnd ()\fC [inline]\fP"

.PP
Definition at line 334 of file BST\&.h\&.
.SS "template<class Comparable > Comparable& \fBBSTItrPost\fP< Comparable >::retrieve ()\fC [inline]\fP"

.PP
Definition at line 333 of file BST\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Projeto AEDA from the source code\&.
