.TH "DuplicateName" 3 "Tue Dec 27 2016" "Version 2" "Projeto AEDA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DuplicateName \- Represents an Invalid Players\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <exceptions\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDuplicateName\fP (const string &n)"
.br
.RI "Full-Constructor\&. "
.ti -1c
.RI "void \fBshow\fP () const"
.br
.RI "Prints the name on the screen\&. "
.in -1c
.SH "Detailed Description"
.PP 
Represents an Invalid Players\&. 
.PP
Definition at line 74 of file exceptions\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DuplicateName::DuplicateName (const string & n)\fC [inline]\fP"

.PP
Full-Constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIn\fP Duplicate n 
.RE
.PP

.PP
Definition at line 81 of file exceptions\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void DuplicateName::show () const\fC [inline]\fP"

.PP
Prints the name on the screen\&. 
.PP
Definition at line 85 of file exceptions\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Projeto AEDA from the source code\&.
