.TH "InvalidDate" 3 "Tue Dec 27 2016" "Version 2" "Projeto AEDA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InvalidDate \- Represents an Invalid \fBDate\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <exceptions\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInvalidDate\fP (unsigned int day, unsigned int month, unsigned int year)"
.br
.RI "Full-Constructor\&. "
.ti -1c
.RI "void \fBshow\fP () const"
.br
.RI "Prints the date on the screen\&. "
.in -1c
.SH "Detailed Description"
.PP 
Represents an Invalid \fBDate\fP\&. 
.PP
Definition at line 25 of file exceptions\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "InvalidDate::InvalidDate (unsigned int day, unsigned int month, unsigned int year)\fC [inline]\fP"

.PP
Full-Constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIday\fP Day of the \fBDate\fP 
.br
\fImonth\fP Month of the \fBDate\fP 
.br
\fIyear\fP Year of the \fBDate\fP 
.RE
.PP

.PP
Definition at line 36 of file exceptions\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void InvalidDate::show () const\fC [inline]\fP"

.PP
Prints the date on the screen\&. 
.PP
Definition at line 40 of file exceptions\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Projeto AEDA from the source code\&.
