.TH "InvalidPlayer" 3 "Tue Dec 27 2016" "Version 2" "Projeto AEDA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InvalidPlayer \- Represents an Invalid Players\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <exceptions\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInvalidPlayer\fP (string name, \fBDate\fP birth)"
.br
.RI "Full-Constructor\&. "
.ti -1c
.RI "void \fBshow\fP () const"
.br
.RI "Prints the \fBPlayer\fP on the screen\&. "
.in -1c
.SH "Detailed Description"
.PP 
Represents an Invalid Players\&. 
.PP
Definition at line 51 of file exceptions\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "InvalidPlayer::InvalidPlayer (string name, \fBDate\fP birth)"

.PP
Full-Constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIname\fP Name of \fBPlayer\fP 
.br
\fIbirth\fP Birthday of \fBPlayer\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void InvalidPlayer::show () const"

.PP
Prints the \fBPlayer\fP on the screen\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Projeto AEDA from the source code\&.
