.TH "/home/oco/Documents/Cprojects/Athletes/projecto - V2/Headers/Level.h" 3 "Tue Dec 27 2016" "Version 2" "Projeto AEDA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/oco/Documents/Cprojects/Athletes/projecto - V2/Headers/Level.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Player\&.h'\fP
.br
\fC#include 'Date\&.h'\fP
.br
\fC#include 'Tournament\&.h'\fP
.br
\fC#include 'Training\&.h'\fP
.br
\fC#include 'BST\&.h'\fP
.br
\fC#include <vector>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <algorithm>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLevel\fP"
.br
.RI "Holds all the information about the \fBClub\fP\&. "
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Francisco Andrade 
.PP
João Almeida
.RE
.PP
Contains the declaration of the class \fBClub\fP and struct \fBhashFuncs\fP 
.PP
Definition in file \fBLevel\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Projeto AEDA from the source code\&.
