.TH "/home/oco/Documents/Cprojects/Athletes/projecto - V2/Headers/Seniors.h" 3 "Tue Dec 27 2016" "Version 2" "Projeto AEDA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/oco/Documents/Cprojects/Athletes/projecto - V2/Headers/Seniors.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Level\&.h'\fP
.br
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSeniors\fP"
.br
.RI "Holds all the information about the \fBLevel\fP \fBSeniors\fP\&. "
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Francisco Andrade 
.PP
João Almeida
.RE
.PP
Contains the declaration of the derived class \fBSeniors\fP 
.PP
Definition in file \fBSeniors\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Projeto AEDA from the source code\&.
