.TH "/home/oco/Documents/Cprojects/Athletes/projecto - V2/Headers/Tournament.h" 3 "Tue Dec 27 2016" "Version 2" "Projeto AEDA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/oco/Documents/Cprojects/Athletes/projecto - V2/Headers/Tournament.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Date\&.h'\fP
.br
\fC#include 'Event\&.h'\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTournament\fP"
.br
.RI "Used to host information about a single \fBTournament\fP\&. "
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Francisco Andrade 
.PP
João Almeida
.RE
.PP
Contains the declaration of the class \fBTraining\fP 
.PP
Definition in file \fBTournament\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Projeto AEDA from the source code\&.
